"""
Catalog of OSINT / security-research services shown on the dashboard.

Each service entry:
  name        - display name
  desc        - one-line description
  inputs      - list of input types it accepts: any of
                "domain", "ip", "hash", "email", "keyword"
  link        - str.format template using {target}, or None if the tool
                has no reliable query-string deep link (opens homepage only)
  live        - name of the live-lookup function in app.py's LIVE_LOOKUPS
                registry, or None if there is no live integration
  key_name    - name of the API key this live lookup needs (looked up from
                the request), or None if no key is required
"""

CATEGORIES = [
    {
        "id": "osint",
        "title": "OSINT и разведка",
        "services": [
            {
                "name": "Shodan",
                "desc": "Internet-connected device search engine",
                "inputs": ["ip", "keyword"],
                "link": "https://www.shodan.io/search?query={target}",
                "live": "shodan",
                "key_name": "shodan",
            },
            {
                "name": "Censys",
                "desc": "Internet-wide host & certificate search",
                "inputs": ["ip", "domain", "keyword"],
                "link": "https://search.censys.io/search?resource=hosts&q={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "IntelX",
                "desc": "Search engine for leaked data & darknet content",
                "inputs": ["domain", "email", "keyword"],
                "link": "https://intelx.io/?s={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "SpiderFoot HX",
                "desc": "Automated OSINT reconnaissance platform",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
            {
                "name": "SecurityTrails",
                "desc": "Historical DNS & domain intelligence",
                "inputs": ["domain"],
                "link": "https://securitytrails.com/domain/{target}/dns",
                "live": "securitytrails",
                "key_name": "securitytrails",
            },
            {
                "name": "FOFA",
                "desc": "Cyberspace asset search engine",
                "inputs": ["keyword"],
                "link": "https://fofa.info/result?qbase64={target_b64}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "ZoomEye",
                "desc": "Cyberspace search engine for devices & services",
                "inputs": ["keyword"],
                "link": "https://www.zoomeye.org/searchResult?q={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "Hunter.io",
                "desc": "Find email addresses associated with a domain",
                "inputs": ["domain"],
                "link": "https://hunter.io/search/{target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "PhoneBook.cz",
                "desc": "Domain, email & phone number search",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
        ],
    },
    {
        "id": "dns",
        "title": "Домены и DNS",
        "services": [
            {
                "name": "crt.sh",
                "desc": "Certificate Transparency log search",
                "inputs": ["domain"],
                "link": "https://crt.sh/?q={target}",
                "live": "crtsh",
                "key_name": None,
            },
            {
                "name": "DNSDumpster",
                "desc": "DNS recon & subdomain discovery",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
            {
                "name": "MXToolbox",
                "desc": "DNS, MX & blacklist lookup toolbox",
                "inputs": ["domain"],
                "link": "https://mxtoolbox.com/SuperTool.aspx?action=a%3a{target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "ViewDNS.info",
                "desc": "DNS, WHOIS & reverse-lookup toolset",
                "inputs": ["domain"],
                "link": "https://viewdns.info/whois/?domain={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "WhoisXML API",
                "desc": "WHOIS & domain intelligence API",
                "inputs": ["domain"],
                "link": "https://www.whoisxmlapi.com/whois-lookup.php?domain={target}",
                "live": None,
                "key_name": None,
            },
        ],
    },
    {
        "id": "web",
        "title": "Анализ сайтов",
        "services": [
            {
                "name": "VirusTotal",
                "desc": "Multi-engine URL / domain / file reputation",
                "inputs": ["domain", "ip", "hash"],
                "link": "https://www.virustotal.com/gui/search/{target}",
                "live": "virustotal",
                "key_name": "virustotal",
            },
            {
                "name": "URLScan.io",
                "desc": "Sandboxed website scanner & search",
                "inputs": ["domain", "ip"],
                "link": "https://urlscan.io/search/#{target}",
                "live": "urlscan",
                "key_name": None,
            },
            {
                "name": "Sucuri SiteCheck",
                "desc": "Website malware & blacklist scanner",
                "inputs": ["domain"],
                "link": "https://sitecheck.sucuri.net/results/{target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "SSL Labs",
                "desc": "TLS/SSL configuration analyzer",
                "inputs": ["domain"],
                "link": "https://www.ssllabs.com/ssltest/analyze.html?d={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "Security Headers",
                "desc": "HTTP security header analyzer",
                "inputs": ["domain"],
                "link": "https://securityheaders.com/?q={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "Mozilla Observatory",
                "desc": "Website security best-practice scanner",
                "inputs": ["domain"],
                "link": "https://developer.mozilla.org/en-US/observatory/analyze?host={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "BuiltWith",
                "desc": "Website technology profiler",
                "inputs": ["domain"],
                "link": "https://builtwith.com/{target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "Wappalyzer",
                "desc": "Technology fingerprinting for websites",
                "inputs": ["domain"],
                "link": "https://www.wappalyzer.com/lookup/{target}/",
                "live": None,
                "key_name": None,
            },
        ],
    },
    {
        "id": "ip",
        "title": "IP и репутация",
        "services": [
            {
                "name": "AbuseIPDB",
                "desc": "IP abuse & blacklist reporting database",
                "inputs": ["ip"],
                "link": "https://www.abuseipdb.com/check/{target}",
                "live": "abuseipdb",
                "key_name": "abuseipdb",
            },
            {
                "name": "GreyNoise",
                "desc": "Internet scanner noise & intent classification",
                "inputs": ["ip"],
                "link": "https://viz.greynoise.io/ip/{target}",
                "live": "greynoise",
                "key_name": "greynoise",
            },
            {
                "name": "IPinfo",
                "desc": "IP geolocation & ASN lookup",
                "inputs": ["ip"],
                "link": "https://ipinfo.io/{target}",
                "live": "ipinfo",
                "key_name": None,
            },
            {
                "name": "Shodan InternetDB",
                "desc": "Free, no-key ports/CVEs/hostnames lookup",
                "inputs": ["ip"],
                "link": "https://internetdb.shodan.io/{target}",
                "live": "internetdb",
                "key_name": None,
            },
            {
                "name": "IPVoid",
                "desc": "IP blacklist & reputation checker",
                "inputs": ["ip"],
                "link": "https://www.ipvoid.com/ip-blacklist-check/",
                "live": None,
                "key_name": None,
            },
        ],
    },
    {
        "id": "leaks",
        "title": "Утечки данных",
        "services": [
            {
                "name": "Have I Been Pwned",
                "desc": "Breach & credential exposure lookup",
                "inputs": ["email", "domain"],
                "link": "https://haveibeenpwned.com/account/{target}",
                "live": "hibp",
                "key_name": None,
            },
            {
                "name": "DeHashed",
                "desc": "Breach data & credential search engine",
                "inputs": ["email", "domain", "keyword"],
                "link": "https://dehashed.com/search?query={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "LeakCheck",
                "desc": "Data breach lookup service",
                "inputs": ["email", "keyword"],
                "link": "https://leakcheck.io/search?query={target}",
                "live": None,
                "key_name": None,
            },
        ],
    },
    {
        "id": "files",
        "title": "Анализ файлов",
        "services": [
            {
                "name": "VirusTotal",
                "desc": "Multi-engine file/hash reputation",
                "inputs": ["hash"],
                "link": "https://www.virustotal.com/gui/search/{target}",
                "live": "virustotal",
                "key_name": "virustotal",
            },
            {
                "name": "Hybrid Analysis",
                "desc": "Free automated malware sandbox",
                "inputs": ["hash"],
                "link": "https://www.hybrid-analysis.com/search?query={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "ANY.RUN",
                "desc": "Interactive malware sandbox",
                "inputs": ["hash"],
                "link": "https://any.run/report/{target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "Joe Sandbox",
                "desc": "Deep malware analysis sandbox",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
        ],
    },
    {
        "id": "vulns",
        "title": "Поиск уязвимостей",
        "services": [
            {
                "name": "CVE Details",
                "desc": "CVE browsing & vulnerability statistics",
                "inputs": ["keyword"],
                "link": "https://www.cvedetails.com/google-search-results.php?q={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "OpenCVE",
                "desc": "CVE tracking & alerting",
                "inputs": ["keyword"],
                "link": "https://www.opencve.io/cve?search={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "Exploit Database",
                "desc": "Public exploit & PoC archive",
                "inputs": ["keyword"],
                "link": "https://www.exploit-db.com/search?q={target}",
                "live": None,
                "key_name": None,
            },
            {
                "name": "NVD",
                "desc": "National Vulnerability Database",
                "inputs": ["keyword"],
                "link": "https://nvd.nist.gov/vuln/search/results?query={target}",
                "live": "nvd",
                "key_name": None,
            },
        ],
    },
    {
        "id": "linux",
        "title": "Онлайн Linux",
        "services": [
            {
                "name": "GitHub Codespaces",
                "desc": "Cloud dev environment",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
            {
                "name": "Replit",
                "desc": "Browser-based IDE & Linux sandbox",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
            {
                "name": "Gitpod",
                "desc": "Ephemeral cloud dev environments",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
            {
                "name": "Google Colab",
                "desc": "Hosted Jupyter/Linux notebooks",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
        ],
    },
    {
        "id": "labs",
        "title": "Онлайн-лаборатории",
        "services": [
            {
                "name": "Hack The Box",
                "desc": "Pentesting labs & CTF platform",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
            {
                "name": "TryHackMe",
                "desc": "Guided cybersecurity learning labs",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
            {
                "name": "PortSwigger Web Security Academy",
                "desc": "Free web security training labs",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
            {
                "name": "OverTheWire",
                "desc": "Wargame-style Linux/security challenges",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
            {
                "name": "Root Me",
                "desc": "Hacking & security challenge platform",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
            {
                "name": "picoCTF",
                "desc": "Beginner-friendly CTF platform",
                "inputs": [],
                "link": None,
                "live": None,
                "key_name": None,
            },
        ],
    },
    {
        "id": "research",
        "title": "Исследование интернета",
        "services": [
            {
                "name": "Wayback Machine",
                "desc": "Historical website snapshot archive",
                "inputs": ["domain"],
                "link": "https://web.archive.org/web/*/{target}",
                "live": "wayback",
                "key_name": None,
            },
            {
                "name": "PublicWWW",
                "desc": "Source-code search engine",
                "inputs": ["keyword"],
                "link": "https://publicwww.com/websites/{target}/",
                "live": None,
                "key_name": None,
            },
            {
                "name": "Netcraft",
                "desc": "Site & hosting intelligence report",
                "inputs": ["domain"],
                "link": "https://sitereport.netcraft.com/?url={target}",
                "live": None,
                "key_name": None,
            },
        ],
    },
]


def homepages():
    """Static homepage URLs for tools with no reliable query-string deep link."""
    return {
        "SpiderFoot HX": "https://www.spiderfoot.net/hx/",
        "PhoneBook.cz": "https://phonebook.cz/",
        "DNSDumpster": "https://dnsdumpster.com/",
        "IPVoid": "https://www.ipvoid.com/",
        "Joe Sandbox": "https://www.joesandbox.com/",
        "GitHub Codespaces": "https://github.com/features/codespaces",
        "Replit": "https://replit.com/",
        "Gitpod": "https://www.gitpod.io/",
        "Google Colab": "https://colab.research.google.com/",
        "Hack The Box": "https://www.hackthebox.com/",
        "TryHackMe": "https://tryhackme.com/",
        "PortSwigger Web Security Academy": "https://portswigger.net/web-security",
        "OverTheWire": "https://overthewire.org/wargames/",
        "Root Me": "https://www.root-me.org/",
        "picoCTF": "https://picoctf.org/",
    }
